// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9uDmA6eYlTSnUxzYys5WmzIteB8bHgbg',
    appId: '1:788972613251:web:e370774e0997230b3b35b6',
    messagingSenderId: '788972613251',
    projectId: 'new-ekart7',
    authDomain: 'new-ekart7.firebaseapp.com',
    storageBucket: 'new-ekart7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_OSiGZJ04f_ED_dH8GaOJSWi3kgPs0M',
    appId: '1:788972613251:android:3fe9ab644a4b31083b35b6',
    messagingSenderId: '788972613251',
    projectId: 'new-ekart7',
    storageBucket: 'new-ekart7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfwCNvlG_VWnFI2hmFbZyELuVhJCUuziM',
    appId: '1:788972613251:ios:13e44e4be3d7b2103b35b6',
    messagingSenderId: '788972613251',
    projectId: 'new-ekart7',
    storageBucket: 'new-ekart7.appspot.com',
    androidClientId: '788972613251-hoja04dq0mvei064eiv4ei6t5ne7lrf2.apps.googleusercontent.com',
    iosClientId: '788972613251-2org1e6ucli4969mir0kjae37gb6fqtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eKartDemoV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfwCNvlG_VWnFI2hmFbZyELuVhJCUuziM',
    appId: '1:788972613251:ios:98e2329a29087d503b35b6',
    messagingSenderId: '788972613251',
    projectId: 'new-ekart7',
    storageBucket: 'new-ekart7.appspot.com',
    androidClientId: '788972613251-hoja04dq0mvei064eiv4ei6t5ne7lrf2.apps.googleusercontent.com',
    iosClientId: '788972613251-i0mfka5avm8d2fp74spjncnhuj88eevv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eKartDemoV1.RunnerTests',
  );
}
